---

# ------------------------------------------------------------------------
# ENSURE THAT ALL OF THE NAGIOS CLIENTS CAN BE REACHED WITH NRPE
# ------------------------------------------------------------------------

- name: "Check that the nagios server can reach NRPE"
  command: /bin/bash -c "{{ check_nrpe_path }} -H {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"
  register: check_nrpe_clients
  always_run: yes
  changed_when: no
  ignore_errors: yes
  with_items: {{ groups['nagios_clients'] }}

- fail: msg="One of the nagios clients cannot be reached with NRPE"
  when: item.rc != 0
  with_items: {{ check_nrpe_clients.results }}


# ------------------------------------------------------------------------
# COPY NAGIOS INVENTORY FILES TO SERVER
# ------------------------------------------------------------------------

- name: "Ensuring that that the nagios directory, {{ nagios_server_host_dir }}/, exists"
  file: 
    path: "{{ nagios_server_host_dir }}/"
    state: directory

- name: "Copying all inventory files to the nagios directory."
  copy: 
    backup: yes
    src: "{{ local_ansible_nagios_dir }}/inventory"
    dest: "{{ nagios_server_host_dir }}/"
    owner: naemon
    group: naemon
    mode: u=rw,g=rw,o=r
  notify: restart nagios




