---

# ------------------------------------------------------------------------
# SERVER CONFIG DEFAULT VARIABLES
# ------------------------------------------------------------------------


# ------------------------------------------------------------------------
# NRPE Vars
# ------------------------------------------------------------------------

# Check NRPE path
check_nrpe_path: "/usr/lib64/nagios/plugins/check_nrpe"


# ------------------------------------------------------------------------
# Nagios Vars
# ------------------------------------------------------------------------

nagios_service_name: "nagios"
nagios_server_host_dir: "/etc/nagios/conf.d/hosts"




